repos:
  - repo: local
    hooks:
      - id: custom-commit-msg
        name: Custom Commit Message Format
        entry: .scripts/check_commit_message.py
        language: python
        stages: [commit-msg]
